### ISSUE TITLE
Erro de pt-BR ali

### ISSUE THREAD

**Issue by ren-gbh** [Allan-CAS/BuscaCep#2]
https://github.com/Allan-CAS/BuscaCep/blob/ff14608611be7e3c5b81ecf5260aab6ccdac0366/BuscaCEP.py#L19

**Comment by Allan-CAS** [comment]
Opa, caro amigo.
Será corrigido no proximo pr.
Obrigado.

**Comment by Allan-CAS** [comment]
correção realizada e merge realizado.
